### ISSUE TITLE
Crash when client conf does not have txmatcher vars setup

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrtxmatcher#37]
2018-11-15 19:22:43.872 [INF] RPCS: RPC method purchaseticket invoked by [::1]:43076
2018-11-15 19:22:49.424 [INF] RPCS: RPC method purchaseticket invoked by [::1]:43082
2018-11-15 19:22:49.429 [INF] DCMX: Session aborted, the client is currently disabled.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d55be]

goroutine 12 [running]:
github.com/decred/dcrwallet/dcrtxclient/service.(*TxService).JoinSplitTx(0x0, 0xc000122c30, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/x/go/src/github.com/decred/dcrwallet/dcrtxclient/service/transaction.go:37 +0x10e
github.com/decred/dcrwallet/wallet.(*Wallet).purchaseTickets(0xc00021c1a0, 0xcc65f7, 0x16, 0x0, 0x2540be400, 0x1, 0x0, 0x0, 0x0, 0x1, ...)
        /home/x/go/src/github.com/decred/dcrwallet/wallet/createtx.go:1972 +0xb8e2
github.com/decred/dcrwallet/wallet.(*Wallet).txCreator(0xc00021c1a0)
        /home/x/go/src/github.com/decred/dcrwallet/wallet/wallet.go:1228 +0x331
created by github.com/decred/dcrwallet/wallet.(*Wallet).Start
        /home/x/go/src/github.com/decred/dcrwallet/wallet/wallet.go:438 +0xd3

**Comment by huyntsgs** [comment]
Fixed in this commit https://github.com/raedahgroup/dcrwallet/commit/f1424ff718b373041b9e223a7198ff5dc846ce2c

**Comment by raedah** [comment]
Tested. Curretly dcrwallet is quiting with no msg. Reason should be shown to the user.
